### PR TITLE
refactor: Avoid direct reference to the name

### PR DESCRIPTION
**Pull request by SukkaW**
The name should not be mentioned even inside the code.

### CODE REVIEW

**Comment by rschristian** [comment]
Hah, sure, why not.

**Comment by SukkaW** [comment]
> Hah, sure, why not.

Because you will get a call out eventually: https://twitter.com/nicoloribaudo/status/1751515040845328752

This is very hilarious because once again, this proves that people just can't mention the name.

**Comment by rschristian** [comment]
Oh I don't mind it being obvious who this refers to -- I'm not following the guy around, linking this in conversations. If it upsets him that there's a site showing what he owns/authors, then that's something he needs to work through. No one's doing any sort of "bullying" and that claim is equally silly (and potentially done for political reasons, but I digress).

While he may throw a bit of a fit and reach out to coworkers of people who've shared it on twitter (which is hilariously sad and petty), I've gotten enough messages from people, those impacted by him in the community as well as former coworkers of his, who've found it funny. It's a joke, and one that I'm not scared of making.

Avoiding even writing his name out in the source is funnier though, I wish I thought of that!

**Comment by rschristian** [comment]
Big fan of nolyfill btw! It's a much more productive way to address the issue.

**Pull request merged**
